// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvwylbvmrhcwktrtidvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2d3lsYnZtcmhjd2t0cnRpZHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTgzNzAsImV4cCI6MjA1NjU5NDM3MH0.0f2w7l-FEoo-n7ywtkHUVYz4_WAld4lA-_i9KenA3M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);